language: node_js

node_js:
  - '10'
  - '11'
  - '12'

script:
  - yarn test

jobs:
  include:
    - stage: release
      node_js: lts/*
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script: yarn semantic-release
