language: node_js

node_js:
  - '14'

script:
  - npm test

jobs:
  include:
    - stage: release
      node_js: lts/*
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script: npm run semantic-release
