name: Test
on: push
jobs:
  build:
    name: Test

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 15.x, 16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: git config --global user.email "you@example.com"
      - run: git config --global user.name "Your Name"
      - run: npm install --global npm@latest
      - run: npm ci
      - run: npm run build
      - run: npm test
